Migration Commit
Sparsh-Goyal-2000/rails_project pull request #1
Opened 2021-08-10 09:08 UTC by Sparsh-Goyal-2000

2021-08-12 11:26 UTC, apekshit-tewathia requested changes

2021-08-12 11:26 UTC, apekshit-tewathia commented on db/migrate/20210810081933_change_enabled_to_product.rb
> +class ChangeEnabledToProduct < ActiveRecord::Migration[6.1]
name of migration not making sense

2021-08-12 11:26 UTC, apekshit-tewathia commented on db/migrate/20210810081933_change_enabled_to_product.rb
> +    change_column_default :products, :enabled, false
Is this reversible? If not, make it reversible

2021-08-12 11:26 UTC, apekshit-tewathia commented on db/migrate/20210810085034_irreversible_migration.rb
> +class IrreversibleMigration < ActiveRecord::Migration[6.1]
Instead of doing this, make a migration that uses something that makes the migration irreversible.

2021-08-12 11:26 UTC, apekshit-tewathia commented on app/views/products/_form.html.erb
> +
why so many extra lines?

2021-08-12 11:26 UTC, apekshit-tewathia commented on app/views/users/_form.html.erb
> +    <%= form.label :email, 'Email:' %>
what is 'Email:' here?

2021-08-12 11:26 UTC, apekshit-tewathia commented on app/views/users/_form.html.erb
> +    <%= form.text_field :email, size: 40 %>
what is `size: 40` here?

2021-08-12 11:26 UTC, apekshit-tewathia commented on db/migrate/20210810081857_add_columns_to_product.rb
> +    add_column :products, :discount_price, :decimal
read about precision and scale and see if it can be used here

2021-08-12 11:26 UTC, apekshit-tewathia commented on app/views/products/_form.html.erb
you have added all these fields in the form and in the db. But, do they get set in your record when you submit the form?

2021-08-12 19:55 UTC, Sparsh-Goyal-2000 reviewed
Sir, I have made the required changes, please review.

2021-08-12 19:55 UTC, Sparsh-Goyal-2000 commented on app/views/products/_form.html.erb
No sir, they were not getting set previously.
Now, I have updated the product_params method to permit new attributes, so they will get set now.

2021-08-12 19:55 UTC, Sparsh-Goyal-2000 commented on app/views/users/_form.html.erb
> +    <%= form.label :email, 'Email:' %>
'Email:' is the label name for the text field where we will get the email of users.

2021-08-12 19:55 UTC, Sparsh-Goyal-2000 commented on app/views/users/_form.html.erb
> +    <%= form.text_field :email, size: 40 %>
Here, size is a parameter to password_field (For HTML, it is <input type = 'password'>)
size is the number of characters wide the input field should be.

2021-08-12 19:55 UTC, Sparsh-Goyal-2000 commented on db/migrate/20210810081933_change_enabled_to_product.rb
> +class ChangeEnabledToProduct < ActiveRecord::Migration[6.1]
New Migration created for the same

2021-08-12 19:55 UTC, Sparsh-Goyal-2000 commented on db/migrate/20210810081933_change_enabled_to_product.rb
> +    change_column_default :products, :enabled, false
It was not reversible.
Changed in the new migration

2021-08-13 14:11 UTC, apekshit-tewathia commented on app/views/users/_form.html.erb
> +    <%= form.label :email, 'Email:' %>
what will happen if i dont pass this?

2021-08-13 14:12 UTC, apekshit-tewathia commented on app/views/users/_form.html.erb
> +    <%= form.text_field :email, size: 40 %>
what will happen if try adding more than 40 characters?

2021-08-13 14:17 UTC, Sparsh-Goyal-2000 commented on app/views/users/_form.html.erb
> +    <%= form.label :email, 'Email:' %>
Sir, It is just the label that will be shown before the email block.
If we don't write this, the user will not get an idea about the value he should enter in the block.

2021-08-13 14:19 UTC, Sparsh-Goyal-2000 commented on app/views/users/_form.html.erb
> +    <%= form.text_field :email, size: 40 %>
Sir, size is the size of the password block, we can enter password of any length.
Changing this size will result in change in block width, not affecting the password entered.

2021-08-16 13:45 UTC, merged