Query
Sparsh-Goyal-2000/rails_project pull request #11
Opened 2021-08-18 12:24 UTC by Sparsh-Goyal-2000

2021-08-19 14:29 UTC, apekshit-tewathia requested changes
Also, post queries and its console logs here as a comment for the following 
Build queries for following- Get All products which are present in atleast one line_item- Get array of product titles which are present in atleast one line item

2021-08-19 14:29 UTC, apekshit-tewathia commented on db/schema.rb
> -  add_foreign_key "products", "catagories"
why this change in this PR?

2021-08-19 14:29 UTC, apekshit-tewathia commented on app/models/product.rb
> +
Add a disabled scope also

2021-08-19 14:29 UTC, apekshit-tewathia commented on app/models/order.rb
> +    scope :by_date, -> (from = Time.zone.now.midnight, to = Time.zone.now.end_of_day) { where created_at: from..to }
Can we use Date objects here instead of time objects?
What is the difference between Time.now, Time.zone.now, Time.current?

2021-08-20 11:42 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +
Yes sir, done

2021-08-20 11:55 UTC, Sparsh-Goyal-2000 commented on app/models/order.rb
> +    scope :by_date, -> (from = Time.zone.now.midnight, to = Time.zone.now.end_of_day) { where created_at: from..to }
Date objects are used now.
3.0.0 :001 > Time.zone
 => #<ActiveSupport::TimeZone:0x00000000038ea898 @name="UTC", @utc_offset=nil, @tzinfo=#<TZInfo::DataTimezone: Etc/UTC>> 
3.0.0 :002 > Time.now
 => 2021-08-20 17:22:30.908743783 +0530 
3.0.0 :003 > Time.current
 => Fri, 20 Aug 2021 11:52:34.814699781 UTC +00:00 
3.0.0 :004 > Time.zone.now
 => Fri, 20 Aug 2021 11:52:40.359239392 UTC +00:00 
3.0.0 :005 > 

Time.now -> gives the system time, does not depend on Time.zone
Time.zone.now -> checks the value of Time.zone or config.time_zone in application.rb
then gives value of time in that zone.
Time.current -> does the same thing

2021-08-20 20:14 UTC, Sparsh-Goyal-2000 commented
![image](https://user-images.githubusercontent.com/64541606/130288683-d003b5e8-11c5-4601-806d-e9162456dcac.png)

2021-08-23 10:00 UTC, apekshit-tewathia requested changes

2021-08-24 08:39 UTC, closed without merging