callbacks commit
Sparsh-Goyal-2000/rails_project pull request #5
Opened 2021-08-12 06:52 UTC by Sparsh-Goyal-2000

2021-08-12 12:04 UTC, apekshit-tewathia requested changes

2021-08-12 12:04 UTC, apekshit-tewathia commented on app/models/user.rb
> +  after_create :notify_with_welcome_email, if: :email?
read why after_create_commit is more ideal in this case and use it instead

2021-08-12 12:04 UTC, apekshit-tewathia commented on app/models/user.rb
> +    UserMailer.created(self).deliver
can we use deliver_later here? what is the difference?

2021-08-12 12:04 UTC, apekshit-tewathia commented on app/models/user.rb
> +    if email.eql?('admin@depot.com')
extract email in  a constant

2021-08-12 12:04 UTC, apekshit-tewathia commented on app/models/user.rb
> +      errors.add(:email, 'can\'t delete or update admin')
message should be specific. as per the action
cant delete admin
or
cant update admin

2021-08-12 12:04 UTC, apekshit-tewathia commented on app/models/user.rb
> +      throw :abort
what is this doing? is this needed here?

2021-08-12 12:04 UTC, apekshit-tewathia commented on test/mailers/previews/user_mailer_preview.rb
> +# Preview all emails at http://localhost:3000/rails/mailers/user_mailer
what is the purpose of this file?

2021-08-13 07:13 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +  after_initialize :set_defaults
Sir, I have used after_initialize, since after initialize, it will have values entered by user, and it can check the nil values and provide the default values accordingly.
Before_validation can also be used for the same.

2021-08-13 07:16 UTC, Sparsh-Goyal-2000 commented on app/models/user.rb
> +      throw :abort
throw: abort
When the callbacks start working, the action is queued for execution. This queue includes the validations, the registered callbacks, and the database operation to be executed.
At any step when we found any error, we have to stop the remaining actions in queue, so we can halt the execution using throw: abort.
I will stop futher actions.

2021-08-13 07:20 UTC, Sparsh-Goyal-2000 commented on app/views/user_mailer/created.text.erb
> +User#created
When we generate new mailer, the views are also set by default. It creates 2 files with extensions 'html.erb' and 'text.erb'. 
While sending mails, in case html file have any issue, then we can use a backup text file for the same.

2021-08-13 07:22 UTC, Sparsh-Goyal-2000 commented on test/mailers/previews/user_mailer_preview.rb
> +# Preview all emails at http://localhost:3000/rails/mailers/user_mailer
This file is created automatically as a test to our mailers function.
We can run tests and check out code working fine or not.

2021-08-13 07:23 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +    self.title = 'abc' unless title
Sir, done

2021-08-13 07:24 UTC, Sparsh-Goyal-2000 commented on app/models/user.rb
> +  after_create :notify_with_welcome_email, if: :email?
after_create_commit, is more ideal, since it will only run when the while transaction gets comitted.

2021-08-13 07:25 UTC, Sparsh-Goyal-2000 commented on app/models/user.rb
> +    UserMailer.created(self).deliver
Yes sir, we can use deliver_later here, it will process the mail working in background so that user don't have to wait while the mail is being processed and sent

2021-08-13 07:25 UTC, Sparsh-Goyal-2000 commented on app/models/user.rb
> +    if email.eql?('admin@depot.com')
Done

2021-08-13 07:25 UTC, Sparsh-Goyal-2000 commented on app/models/user.rb
> +      errors.add(:email, 'can\'t delete or update admin')
Done.

2021-08-13 14:50 UTC, apekshit-tewathia commented on app/models/product.rb
> +  after_initialize :set_defaults
try to find difference between the two you've mentioned. also, can we use before_save,after_save etc to achieve the same?

2021-08-13 14:50 UTC, apekshit-tewathia commented on app/models/user.rb
> +  after_create :notify_with_welcome_email, if: :email?
let's discuss this

2021-08-13 14:54 UTC, apekshit-tewathia requested changes

2021-08-13 14:54 UTC, apekshit-tewathia commented on app/models/user.rb
> +  def check_admin_while_update
find a better name for this

2021-08-13 14:54 UTC, apekshit-tewathia commented on app/controllers/users_controller.rb
> +      redirect_to users_url, notice: @user.errors['email']
use alert here instead of notice
what is the difference?

2021-08-14 08:48 UTC, Sparsh-Goyal-2000 commented on app/models/user.rb
> +  def check_admin_while_update
Sir, name changed

2021-08-14 08:51 UTC, Sparsh-Goyal-2000 commented on app/controllers/users_controller.rb
> +      redirect_to users_url, notice: @user.errors['email']
alert and notice are both flash message which help to pass any message to new redirected or rendered page.
These both are the keys of hash - flash.
They are not same in terms of usage.
But, we generally use notice to confirm about any successful operation and alert to pass an error message.

2021-08-14 09:03 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +  after_initialize :set_defaults
after_initialize -> called directly when calling new or loading data from database. It is not necessary to try to validate or save this record, this callback will be called just after the object is created.
before_validation -> this is called when we try to validate the record or save the record since it also requires validation.
before_save -> before_save is called after validating the record, but if the values are blank, it will not pass the validations, so we can't use this callback.
after_save -> this is called after saving the record, we can't use this callback too, since if the record is not valid, it can't be saved.

2021-08-17 13:23 UTC, apekshit-tewathia commented on app/views/user_mailer/created.text.erb
> +User#created
check if we can force text format here

2021-08-19 14:05 UTC, apekshit-tewathia commented
why does this PR have validation PR changes. Fix the PR

2021-08-20 11:57 UTC, closed without merging