Validation
Sparsh-Goyal-2000/rails_project pull request #6
Opened 2021-08-12 11:16 UTC by Sparsh-Goyal-2000

2021-08-12 11:52 UTC, apekshit-tewathia requested changes

2021-08-12 11:52 UTC, apekshit-tewathia commented on app/models/line_item.rb
> +  validates :product_id, uniqueness: {
what will happen if cart_id is nil?

2021-08-12 11:52 UTC, apekshit-tewathia commented on app/models/product.rb
> +class UrlValidator < ActiveModel::EachValidator
Put this in another file. This shouldn't be in models/product.rb

2021-08-12 11:52 UTC, apekshit-tewathia commented on app/models/product.rb
> +class ComparePriceValidator < ActiveModel::Validator
another file

2021-08-12 11:52 UTC, apekshit-tewathia commented on app/models/product.rb
> +  VALID_PERMALINK_REGEX = /\A([a-zA-Z]+-){2,}([a-zA-z]+)\z/
numbers are still allowed. only special characters are not allowed

2021-08-12 11:52 UTC, apekshit-tewathia commented on app/models/product.rb
> +  VALID_DESCRIPTION_REGEX = /\A(\w+ ){4,9}(\w+)\z/
what if there is more than one space in between words, or spaces in the beginning or in the end?

2021-08-12 11:52 UTC, apekshit-tewathia commented on app/models/product.rb
> +  include ActiveModel::Validations
why is this needed?

2021-08-12 11:52 UTC, apekshit-tewathia commented on app/models/product.rb
> +  validates :permalink, uniqueness: true, allow_nil: true, format: {
what is allow_nil doing here?

2021-08-12 11:52 UTC, apekshit-tewathia commented on app/models/product.rb
> +  validates :price, allow_nil: true, numericality: {
what is the difference between allow_nil and allow_blank?

2021-08-12 11:52 UTC, apekshit-tewathia commented on app/models/product.rb
> +    greater_than_or_equal_to: 0.01,
extract 0.01 in a constant

2021-08-12 11:52 UTC, apekshit-tewathia commented on app/models/product.rb
> +    only_integer: true
Explain what this is doing

2021-08-12 11:52 UTC, apekshit-tewathia commented on app/models/product.rb
> +    message:  'should have minimum 3 words separated by hyphen'
extract all error messages in constants

2021-08-12 11:52 UTC, apekshit-tewathia commented on app/models/product.rb
> +    unless value =~ %r{\.(gif|jpg|png)\Z}i
regex in constant

2021-08-12 11:52 UTC, apekshit-tewathia commented on app/models/product.rb
> +    return if record.price.nil? || record.discount_price.nil?
is it possible that record.price is a string here?give reason

2021-08-12 11:52 UTC, apekshit-tewathia commented on app/models/user.rb
> +		message: 'is not an email'
Is it necessary to give an error message here?

2021-08-12 21:05 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +  validates :permalink, uniqueness: true, allow_nil: true, format: {
Sir, allow_nil option skips the validation when the value being validated is nil.
If permalink entered by the user is nil, the validation will not run on that value.

2021-08-12 21:09 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +  validates :price, allow_nil: true, numericality: {
allow_nil skips validation if value is nil.
allow_blank skips validation if value is nil or blank(empty string ' ').

2021-08-12 21:11 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +    only_integer: true
numericality validates only integer values.
only_integer check if the value given is an integer or not, 
if the value is not integer, it tries to convert into integer using float.

2021-08-12 21:12 UTC, Sparsh-Goyal-2000 commented on app/models/user.rb
> +		message: 'is not an email'
It is not necessary.
default error message is 'is invalid'.

2021-08-12 21:13 UTC, Sparsh-Goyal-2000 commented on app/models/line_item.rb
> +  validates :product_id, uniqueness: {
We can use allow_nil: true option, so that it does not validate if the value is nil.

2021-08-12 21:14 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +class UrlValidator < ActiveModel::EachValidator
Sir, done.

2021-08-12 21:14 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +class ComparePriceValidator < ActiveModel::Validator
Done

2021-08-12 21:14 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +  VALID_PERMALINK_REGEX = /\A([a-zA-Z]+-){2,}([a-zA-z]+)\z/
Regex Improved

2021-08-12 21:14 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +  VALID_DESCRIPTION_REGEX = /\A(\w+ ){4,9}(\w+)\z/
Regex Improved

2021-08-12 21:16 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +  include ActiveModel::Validations
I have removed this line since i have implemented the methods in another file.
This include was not needed.

2021-08-12 21:16 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +    greater_than_or_equal_to: 0.01,
Sir, done

2021-08-12 21:17 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +    return if record.price.nil? || record.discount_price.nil?
Since for price, we have used only_integer: true in numericality, so it will never have string value.

2021-08-13 14:31 UTC, apekshit-tewathia requested changes

2021-08-13 14:31 UTC, apekshit-tewathia commented on app/models/custom_validations.rb
> +    class UrlValidator < ActiveModel::EachValidator
create two separate files, url_validator and compare_price_validator and put them in app/validators

2021-08-13 14:31 UTC, apekshit-tewathia commented on app/models/product.rb
> +  VALID_PERMALINK_REGEX = /\A(\w+-){2,}(\w+)\z/
this will also allow `_` which is a special character

2021-08-13 14:31 UTC, apekshit-tewathia commented on app/models/product.rb
> +  VALID_DESCRIPTION_REGEX = /\A( *\w+ +){4,9}( *\w+ *)\z/
can we use some character class instead of a space ` ` here

2021-08-13 14:32 UTC, apekshit-tewathia commented on app/models/product.rb
> +    return if record.price.nil? || record.discount_price.nil?
let's discuss this in next call

2021-08-13 14:33 UTC, apekshit-tewathia commented on app/models/product.rb
> +  include ActiveModel::Validations
it should not be needed even if those were in the same file. Check and confirm

2021-08-13 14:33 UTC, apekshit-tewathia commented on app/models/product.rb
> +  validates :permalink, uniqueness: true, allow_nil: true, format: {
If we don't enter a value in form, will it be nil or blank by default?

2021-08-14 07:27 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +  VALID_DESCRIPTION_REGEX = /\A( *\w+ +){4,9}( *\w+ *)\z/
Yes sir, regex improved, we can use \s for the whitespace character

2021-08-14 07:28 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +  VALID_PERMALINK_REGEX = /\A(\w+-){2,}(\w+)\z/
yes sir, improved, not using [a-zA-Z0-9] for the same.

2021-08-14 07:28 UTC, Sparsh-Goyal-2000 commented on app/models/custom_validations.rb
> +    class UrlValidator < ActiveModel::EachValidator
Done sir

2021-08-14 07:32 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +    only_integer: true
When left blank,
string values are taken as blank, so we can use allow_blank for the string values.
other type of values are assumed as nil, so we can use allow_nil for them

2021-08-17 19:18 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +  VALID_PERMALINK_REGEX = /\A([[:alnum:]]+-){2,}([[:alnum:]]+)\z/
[[:alnum:]]
character class for [a-zA-Z0-9]
used

2021-08-17 19:19 UTC, Sparsh-Goyal-2000 commented on app/validators/compare_price_validator.rb
> +    elsif record.price < record.discount_price
Checking for a valid price value in this validation again.

2021-08-17 19:21 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +    only_integer: true
If we enter price as 2.3
It is giving error that Price must be an integer

2021-08-19 14:03 UTC, apekshit-tewathia requested changes

2021-08-19 14:03 UTC, apekshit-tewathia commented on app/models/product.rb
> +  validates :price, numericality: {
what if price is not present?

2021-08-19 14:03 UTC, apekshit-tewathia commented on app/models/product.rb
> +  validates :permalink, uniqueness: true, allow_blank: true, format: {
use with_options block and add all allow_blank validations in that block

2021-08-19 14:03 UTC, apekshit-tewathia commented on app/models/product.rb
> +  has_many :line_items
follow the order Assocations, Validations, Callbacks

2021-08-19 14:03 UTC, apekshit-tewathia commented on app/models/product.rb
> +require_relative '../validators/url_validator'
this should not be needed. let's discuss this

2021-08-20 08:28 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +  has_many :line_items
Done

2021-08-20 08:29 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +require_relative '../validators/url_validator'
Removed.

2021-08-20 08:29 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +  validates :permalink, uniqueness: true, allow_blank: true, format: {
Done.

2021-08-20 08:29 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +  validates :price, numericality: {
Improved.

2021-08-20 08:29 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +  validates :title, presence: true, uniqueness: true
Done.

2021-08-23 09:11 UTC, apekshit-tewathia requested changes

2021-08-23 09:11 UTC, apekshit-tewathia commented on app/models/product.rb
> +    }, if: :discount_price
use predicate method instead

2021-08-23 09:11 UTC, apekshit-tewathia commented on app/models/product.rb
> +  with_options allow_nil: true do
can we use allow_blank here instead?

2021-08-23 09:11 UTC, apekshit-tewathia commented on app/models/product.rb
> +    validates :description, format: {
can description be empty?

2021-08-23 19:01 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +    }, if: :discount_price
Sir, Done.

2021-08-23 19:02 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +  with_options allow_nil: true do
Yes sir, we can use allow_blank also.

2021-08-23 19:03 UTC, Sparsh-Goyal-2000 commented on app/models/product.rb
> +    validates :description, format: {
In my previous submitted code, the description can be empty, but now i have modified it and it can't be empty, so added a presence validation for description.

2021-08-24 14:28 UTC, merged