Associations Exercise Submitted 1st
Sparsh-Goyal-2000/rails_project pull request #7
Opened 2021-08-13 15:34 UTC by Sparsh-Goyal-2000

2021-08-17 12:34 UTC, apekshit-tewathia requested changes

2021-08-17 12:34 UTC, apekshit-tewathia commented on app/models/cart.rb
> +    has_many :enabled_products, -> {where enabled: true}, class_name: 'Products', through: :line_items
can we use source here?
leave space around curly braces

2021-08-17 12:34 UTC, apekshit-tewathia commented on app/models/line_item.rb
> +  belongs_to :cart, counter_cache: :line_items_count
can i give counter_cache: true here?

2021-08-17 12:34 UTC, apekshit-tewathia commented on db/migrate/20210813100424_add_user_ref_to_order.rb
> +    add_reference :orders, :user, foreign_key: true
whenever you add such migration, make sure current data in the db stays valid. Let's discuss this

2021-08-17 12:34 UTC, apekshit-tewathia commented on config/routes.rb
> +  get 'users/orders', to: 'users#show_user_orders'
make use of resources block to do this

2021-08-17 12:34 UTC, apekshit-tewathia commented on app/controllers/users_controller.rb
> +  def show_user_line_items
rename this to `line_items`

2021-08-17 12:34 UTC, apekshit-tewathia commented on app/controllers/users_controller.rb
> +  def show_user_orders
rename this to `orders`

2021-08-17 12:34 UTC, apekshit-tewathia commented on app/controllers/users_controller.rb
> +    @items = @user.line_items.paginate(page: params[:page], per_page: 5)
extract 5 in a constant

2021-08-17 12:34 UTC, apekshit-tewathia commented on app/controllers/users_controller.rb
> +    def set_logged_in_user
extract this somewhere so that this can be used in multiple controllers

2021-08-20 13:13 UTC, apekshit-tewathia requested changes

2021-08-21 07:33 UTC, Sparsh-Goyal-2000 commented on app/controllers/users_controller.rb
> +    @items = @user.line_items.paginate(page: params[:page], per_page: ENTRY_PER_PAGE)
Yes sir, default per_page value is 30.
We can change the value in the method definition defined in will_paginate gem

2021-08-21 07:34 UTC, Sparsh-Goyal-2000 commented on app/views/users/line_items.html.erb
> +            <td> <%= line_item.product.title %> </td>
Yes sir, now this is more optimised since we have included products one time, so we don't need to ask for products in loop.

2021-08-21 07:35 UTC, Sparsh-Goyal-2000 commented on app/controllers/users_controller.rb
> +  ENTRY_PER_PAGE = 5
Yes sir, now defined in Application Controller.

2021-08-21 07:36 UTC, Sparsh-Goyal-2000 commented on app/controllers/orders_controller.rb
> +      parameters = params.require(:order).permit(:name, :address, :email, :pay_type)
Now user_id is passed only during creating a order.

2021-08-23 09:53 UTC, apekshit-tewathia requested changes

2021-08-23 09:53 UTC, apekshit-tewathia commented on config/routes.rb
> +  get 'users/orders', to: 'users#orders'
fix this now that you've read about routing

2021-08-23 09:53 UTC, apekshit-tewathia commented on db/migrate/20210813100424_add_user_ref_to_order.rb
> +    add_reference :orders, :user, foreign_key: true
still to be discussed

2021-08-23 09:53 UTC, apekshit-tewathia commented on app/views/users/orders.html.erb
> +    <% @orders.includes(:line_items).each do |order| %>
can we include products also here?
what is the difference after doing so?

2021-08-23 09:53 UTC, apekshit-tewathia commented on app/controllers/orders_controller.rb
> +    parameters[:user_id] = session[:user_id]
can you use set_logged_in user here?

2021-08-23 09:53 UTC, apekshit-tewathia commented on app/controllers/orders_controller.rb
> +    @order = Order.new(parameters)
create a method called create_params and do the params processing in that method

2021-08-23 09:53 UTC, apekshit-tewathia commented on app/controllers/application_controller.rb
> +    ENTRY_PER_PAGE = 5
define these generic constants in constants.rb

2021-08-23 09:53 UTC, apekshit-tewathia commented on app/controllers/users_controller.rb
> +    @items = @user.line_items.paginate(page: params[:page], per_page: ENTRY_PER_PAGE)
find an easier way. we dont need to modify the gem for this. read the documentation

2021-08-24 06:09 UTC, Sparsh-Goyal-2000 commented on config/routes.rb
> +  get 'users/orders', to: 'users#orders'
Sir, Done.

2021-08-24 06:10 UTC, Sparsh-Goyal-2000 commented on app/views/users/orders.html.erb
> +    <% @orders.includes(:line_items).each do |order| %>
If we include products here, it search for any associated products with orders and that does not exist.

2021-08-24 06:11 UTC, Sparsh-Goyal-2000 commented on app/controllers/orders_controller.rb
> +    parameters[:user_id] = session[:user_id]
Yes sir, used.

2021-08-24 06:11 UTC, Sparsh-Goyal-2000 commented on app/controllers/orders_controller.rb
> +    @order = Order.new(parameters)
SIr, done.

2021-08-24 06:11 UTC, Sparsh-Goyal-2000 commented on app/controllers/application_controller.rb
> +    ENTRY_PER_PAGE = 5
Done.

2021-08-24 06:20 UTC, Sparsh-Goyal-2000 commented on app/controllers/users_controller.rb
> +    @items = @user.line_items.paginate(page: params[:page], per_page: ENTRY_PER_PAGE)
Sir, we can change this value by setting this parameter like this.
WillPaginate.per_page = 10
we can do this in constants.rb or any particular file where it is required.

2021-08-24 14:19 UTC, apekshit-tewathia commented on config/routes.rb
> +  namespace :users do
use resources here

2021-08-24 14:19 UTC, apekshit-tewathia commented on app/views/users/orders.html.erb
> +    <% @orders.includes(:line_items).each do |order| %>
read about it

2021-08-25 05:45 UTC, Sparsh-Goyal-2000 commented on config/routes.rb
> +    get :line_items, on: :collection
Now resources block used for the same.

2021-08-25 05:46 UTC, Sparsh-Goyal-2000 commented on app/views/users/orders.html.erb
> +    <% @orders.includes(line_items: :product).each do |order| %>
product table also loaded in starting

2021-08-25 14:46 UTC, merged